FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
# Polling for file changes in Docker (Linux)
ENV WATCHPACK_POLLING=true
CMD ["npm", "run", "dev"]
